function [comedy_movies, drama_movies, romance_movies] = genre_samples
%Stores a struct for the three genres (movies from the population
%matrices);IMDB ratings
  comedy_movies = struct('Movie_Names', ['Pretty Woman', 'Dick Tracy', 'Air
  America',...
  'The Marrying Man', 'Oscar', 'Barton Fink', 'The Player', 'Dead Alive', ...
  'Death Becomes Her', 'Groundhog Day', 'Sleepless in Seattle', 'Short
  Cuts',...
  'Four Weddings and a Funeral', 'Three Colors: White', 'The Adventrues of
  Priscilla, Queen of the Desert',...
  'French Kiss', 'Forget Paris','To Die For', 'The Birdcage', 'The Mirror Has
  Two Faces',...
  'Chasing Amy', 'Liar Liar', 'The Full Monty', 'Stiff Upper Lips', ...
  'The Big Lebowski', 'Buffalo ''66', 'Torrente, el brazo tonto de la
  ley',...
  'You or Me', 'Go', 'Analyze This', 'High Fidelity', 'O Brother, Where Art
  Thou', ...
  'Snatch', 'Glass Tiger', 'The Mexican','Shrek','Chicago', 'Confessions of a
  Dangerous Mind', ...
  'Torremolinnos 73', 'Love Actually', 'Ferpect Crime','A Series of
  Unfortunate Events', ...
  'Mrs.Henderson Persents', 'Shortbus', 'Stranger Than Fiction','Bernard and
  Doris', ...
  'Death at a Funeral','Mrs.Ratcliffe''s Revolution', 'Juno', 'In
  Bruges', ...
  'Miss Pettigrew Lives for a Day', 'Vicky Cristina Barcelona', 'I Love You
  Phillip Moris', ...
  'The Hangover','Beginners','Midnight in Paris','The Artist','Horrible
  Bosses', 'Honest Trailers', ...
  'Teen Titans Go!', 'Brooklyn Nine-Nine', 'Bojack Horseman', 'The
  Ranch','Private Eyrs', ...
  'Atlanta', 'This Is Us', 'The Grand Tour', 'Scott thhe Woz', ...
  'DuckTales', 'Sick of It', 'Gordon, Gino & Fred''s Road Trip', 'Sex
  Education', ...
  'The Other Two', 'What We Do in the Shadows', 'After Life', 'DC Super Hero
  Girls', ...
  'Ghosts', 'Dead to Me', 'Spider-Man:Far from Home', 'Scooby-Doo and Guess
  Who?', ...
  'Family Reunion', 'The Boys', 'James May: Our Main in Italy', ...
  'Sonic the Hedgehog', 'WandaVision', 'Power Rangers Dino Fury'], ...
  'Rating', [7.1, 6.2, 5.8, 5.7, 6.5, 7.6 ...
  7.5, 7.5, 6.6, 8, 6.8, 7.7, 7.1, 7.6, 7.5, 6.6, 6.5, 6.8, 7.2, 6.6,
  7.2, ...
  6.9, 7.2, 6.2, 8.1, 7.4, 6.8, 5.2, 7.2,
  6.7,7.4,7.7,8.2,7.7,6.1,7.9,7.2, ...
  7.0,6.5,7.6,7.1,6.8,7.0,6.4,7.5,6.5,7.3,5.7,7.5,7.9,7.0,7.1,6.6,7.7, ...
  7.2,7.7,7.9,6.9,7.3, 8.5, 5.4,8.4,8.8, 7.5, 7.3, 8.6, 8.7, 8.7, 9.3, ...
  8.3,7.4,8.4,8.3,7.8,8.6,8.4,7.3,8.3,8.0,7.4,7.4,6.6,8.7,8.2,6.5,7.9,6.7]);
  drama_movies = struct('Movie_Names', ['White Hunter Black Heart', 'Goodfellas',
  ...
  'The Grifters','Sleeping with the Enemy', 'The Doors', 'Barton Fink' ...
  'Shining Through', 'Final Analysis', 'Basic Instinct', 'Groundhog Day', ...
  'The Vanishing', 'Falling Down', 'Indecent Proposal', 'The Trial', ...
  'Guilty as Sin', 'Intersection', 'Four Weddings and a Funeral', 'Three
  Colors: White',...
  'The Usual Suspects', 'The Basketball Diaries', 'Dolores Claiborne', ...
  'Trainspotting', 'Primal Fear', 'A Time to Kill','Chasing Amy', 'Absolute
  Power', ...
  'Donnie Brasco', 'Buffalo ''66', 'Great Expectations', 'A Perfect
  Murder', ...
  'Payback', '8MM','True Crime', 'American Psycho', 'High Fidelity', ...
  'Gladiator','The Mexican', 'Blow','Moulin Rouge!', 'City of God', ...
  'Gangs of New York','Confessions of a Dangerous Mind','The Life of David
  Gale', ...
  'Torremolinos 73', 'The Dreamers', 'Eternal Sunshine of the Spotless Mind',
  ...
  'Bad Education', 'De-Lovely','Match Point','Cinderella Man','Batman
  Begins', ...
  'Shortbus','The Queen','Perfume:The Story of a Murder', 'The
  Counterfeiters', ...
  'No Country for Old Men','We Own the Night','In Bruges','The Bank Job', ...
  'Vicky Cristina Barcelona','I Love You Phillip Morris', 'The Countess','22
  Bullets', ...
  'Wall Street: Money Never Sleeps','Beginners','Kill the Irishman','The
  Artist', ...
  'The Tree of Life', 'Revolution', 'Arrow', 'Shetland','The Blacklist', ...
  'The Originals', 'Boschh','BoJack Horseman', 'The Flash','Chicago Med', ...
  'Lucifer','Jack Irish','The Ranch','Private Eyes','Animal Kingdom',
  'Atlanta','This Is Us', ...
  'Riverdale', 'The Good Fight', 'American Gods', 'Money Heist', 'Ozark', ...
  'Star Trek: Discovery', 'SEAL Team','S.W.A.T.', '9-1-1','The Resident'],
  'Rating', [6.5, 8.7, 6.9, 6.2, 7.2, ...
  7.6, 6.4, 5.9, 7.0, 8.0, 6.3, 7.6,6.0, 6.0, 5.6, 5.3, 7.1, 7.6, 8.5, ...
  7.3, 7.4, 8.1, 7.7, 7.5, 7.2, 6.7, 7.7, 7.4, 6.8, 6.6,7.1, 6.6, 6.6, ...
  7.6,7.4,8.5,6.1,7.5,7.6,8.6,7.5,7.0,7.5,6.5,7.1,7.4,6.6,6.7,7.6,8.0, ...
  8.2,7.3,7.5,7.5,7.5,8.2,7.8,6.6,6.2,6.6,6.2,7.2,7.8,7.0,7.9,6.8,7.0, ...
  7.5,8.2,8.0,8.3,8.5,8.8,7.5,7.5,7.6,8.1,7.8,7.5,7.3,8.2,8.6,8.7,6.6,8.3,7.6,8.2,8.5
  ,7.0,7.8, ...
  7.1,7.8,7.8]);
  romance_movies = struct('Movie_Names', ['Pretty Woman', 'Dick Tracy',
  'Havana',...
  'The Marrying Man', 'Doc Hollywood', 'High Heels', 'Shining Through', ...
  'Far and Away', 'The Crying Game', 'Groundhog Day', 'Indecent
  Proposal', ...
  'Sleepless in Seattle','Intersection', 'Four Weddings and a Funeral', ...
  'Three Colors: White', 'The Quick and the Dead', 'French Kiss', 'Total
  Eclipse', ...
  'Romeo + Juliet', 'The Mirror Has Two Faces','Chasing Amy', 'She''s So
  Lovely', ...
  'Wilde',' Lolita', 'Great Expectations','The Horse Whisperer', 'The Last
  Days of Disco', ...
  'You or Me', 'Notting Hill', 'Summer of Sam', 'High Fidelity', 'Before
  Night Fall', ...
  'Cast Away', 'The Mexican','Shrek','Moulin Rouge!','Confessions of a
  Dangerous Mind', ...
  'The Hours','The Dreamers','Love Actually','Big Fish','Eternal Sunshine of
  thhe Spotless Mind', ...
  'Closer','Match Point','Cinderella Man','An Unfinished Life','Brokeback
  Mountain', ...
  'Shortbus','Stranger Than Fiction','Bernard and Doris','Miss Pettigrew
  Lives for a Day', ...
  'Vicky Cristina Barcelona','Slumdog Millionaire','The Curious Case of
  Benjamin Button', ...
  'I Love You Phillip Morris','Beginners','Midnight in Paris','The
  Artist', ...
  'Revoluation','This is Us','Riverdale','Station 19','Roswell, New
  Mexico', ...
  'Virgin River', 'WandaVision','First Love',], 'Rating', [7.1, 6.2, ...
  6.1,5.7,6.3,7.0,6.4,6.6,7.2,8.0,6.0,6.8,5.3,7.1,7.6,6.5,6.6,6.5,6.7, ...
  6.6,7.2,5.9,6.9,6.8,7.4,6.8,6.7,5.2,7.2,6.7,7.4,7.1,7.8,6.1,7.9,7.6, ...
  7.0,7.5,7.1,7.6,8.0,8.3,7.2,7.6,8.0,7.0,6.4,7.5,6.5,7.0,7.1,8.0,6.6, ...
  7.2,7.7,7.9,7.0,8.7,6.6,6.9,6.3,7.4,7.9,8.4]);
end
